#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
RTSP components verification script for DS-SOP Docker image.
Can be executed on the host (spawns Docker container automatically)
or inside the container (performs actual diagnostics).

NOTE: This file is bind-mounted standalone into the ds-sop container
(`-v <script>:/verify.py`), so it MUST stay self-contained and cannot import a shared
helper. The H.264 encoder detection (check_x264enc_encoder / check_gstreamer_elements)
and the RTSP server instantiation (check_rtsp_instantiation) deliberately mirror the
RTSP streaming-output logic generated by the ds-sop-skills skill (ds-sop-skills § 18 —
../ds-sop-skills/deepstream-sop/references/skill_18_rtsp_streaming_output.md) and
rtsp_tools/rtsp_server.py;
keep the encoder preference order consistent across all three when editing.
"""

import sys
import os
import subprocess
import socket

def run_host_driver():
    """Spawns the Docker container and runs this script inside it."""
    script_path = os.path.abspath(__file__)
    print(f"=== Host Driver: Launching container and mounting verification script ===")
    print(f"Script: {script_path}")
    print(f"Image:  ds-sop:1.0.0\n")
    
    cmd = [
        "docker", "run", "--rm",
        "--gpus", "all",
        "-v", f"{script_path}:/verify.py",
        "--entrypoint", "python3",
        "ds-sop:1.0.0",
        "/verify.py", "--inside-container"
    ]
    
    # Detect docker wrapper prefix
    docker_prefix = []
    try:
        subprocess.run(["docker", "ps"], capture_output=True, check=True, timeout=5)
    except Exception:
        try:
            subprocess.run(["sg", "docker", "-c", "docker ps"], capture_output=True, check=True, timeout=5)
            docker_prefix = ["sg", "docker", "-c"]
        except Exception:
            try:
                subprocess.run(["sudo", "docker", "ps"], capture_output=True, check=True, timeout=5)
                docker_prefix = ["sudo"]
            except Exception:
                print("❌ Error: Cannot connect to Docker daemon. Please verify Docker is running and check permissions.")
                return 1

    if docker_prefix == ["sg", "docker", "-c"]:
        import shlex
        escaped_cmd = " ".join(shlex.quote(arg) for arg in cmd)
        full_cmd = ["sg", "docker", "-c", escaped_cmd]
    else:
        full_cmd = docker_prefix + cmd

    try:
        result = subprocess.run(full_cmd, capture_output=False, check=True)
        return result.returncode
    except subprocess.CalledProcessError as e:
        print(f"\n❌ Container verification run failed with exit code {e.returncode}")
        return e.returncode
    except FileNotFoundError:
        print("❌ Error: 'docker' command not found. Please install Docker first.")
        return 1

def check_gst_rtsp_server():
    print("Check 1 — Importing GstRtspServer...", end=" ")
    try:
        import gi
        gi.require_version('GstRtspServer', '1.0')
        from gi.repository import GstRtspServer
        print("✅ OK")
        return True
    except Exception as e:
        print("❌ FAIL")
        print(f"   Error details: {e}")
        print("   Auto-fix: Add 'libgstrtspserver-1.0-dev' and 'gir1.2-gst-rtsp-server-1.0' to Dockerfile apt install block and rebuild.")
        return False

def check_x264enc_encoder():
    print("Check 2 — Searching for x264enc software encoder...", end=" ")
    try:
        import gi
        gi.require_version('Gst', '1.0')
        from gi.repository import Gst
        Gst.init(None)
        if Gst.ElementFactory.find('x264enc'):
            print("✅ OK")
            return True
        else:
            raise ValueError("x264enc element not found")
    except Exception as e:
        print("❌ FAIL")
        print(f"   Error details: {e}")
        print("   Auto-fix: Install 'gstreamer1.0-plugins-ugly gstreamer1.0-plugins-bad gstreamer1.0-libav', then 'rm -rf ~/.cache/gstreamer-1.0/registry.*.bin' and rebuild.")
        return False

def check_protobuf_stubs():
    print("Check 3 — Checking Protobuf stubs...", end=" ")
    try:
        from nvds_action_detector.protos import nv_pb2, ext_pb2
        nv_types = len(nv_pb2.DESCRIPTOR.message_types_by_name)
        ext_types = len(ext_pb2.DESCRIPTOR.message_types_by_name)
        print(f"✅ OK (nv_pb2 has {nv_types} types, ext_pb2 has {ext_types} types)")
        return True
    except Exception as e:
        print("❌ FAIL")
        print(f"   Error details: {e}")
        print("   Auto-fix: Inside container, run:")
        print("   cd /opt/nvidia/nvds_sop/nvds_action_detector/protos/ && protoc -I. --python_out=. nv.proto ext.proto && sed -i 's/^import nv_pb2 as/from . import nv_pb2 as/' ext_pb2.py")
        print("   Ensure the Dockerfile RUN step compiles them and rebuild.")
        return False

def check_gstreamer_elements():
    print("Check 4 — Verifying all required GStreamer elements registered...", end=" ")
    try:
        import gi
        gi.require_version('Gst', '1.0')
        from gi.repository import Gst
        Gst.init(None)
        required = ['x264enc', 'rtph264pay', 'udpsink', 'nvvideoconvert', 'jpegenc', 'rtpjpegpay']
        missing = [e for e in required if not Gst.ElementFactory.find(e)]
        if not missing:
            print("✅ OK (all elements found)")
            return True
        else:
            print("❌ FAIL")
            print(f"   Missing elements: {missing}")
            print("   Auto-fix: Run 'rm -rf ~/.cache/gstreamer-1.0/registry.*.bin && gst-inspect-1.0 > /dev/null 2>&1'")
            print("   and make sure relevant gstreamer1.0-plugins-* packages are installed in Dockerfile.")
            return False
    except Exception as e:
        print(f"❌ FAIL (exception: {e})")
        return False

def check_shared_libraries():
    print("Check 5 — Verifying no broken shared library dependencies...", end=" ")
    try:
        # Run ldd to find any missing libraries
        cmd = "ldd /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgst*.so 2>/dev/null | grep 'not found'"
        proc = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        stdout, _ = proc.communicate()
        
        if not stdout.strip():
            print("✅ OK")
            return True
        else:
            print("⚠️ WARNING (Ignored)")
            print("   Some optional/unused plugins have broken dependencies:")
            for line in stdout.strip().split('\n')[:5]:
                print(f"     {line}")
            print("   These plugins are not required for DS-SOP, so this warning is safely ignored.")
            return True
    except Exception as e:
        print(f"⚠️ WARNING (exception: {e})")
        return True

def check_rtsp_instantiation():
    print("Check 6 — Testing RTSP server instantiation & port binding...", end=" ")
    try:
        import gi
        gi.require_version('Gst', '1.0')
        gi.require_version('GstRtspServer', '1.0')
        from gi.repository import Gst, GstRtspServer
        Gst.init(None)
        
        # Find an open port
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
            s.bind(('', 0))
            port = s.getsockname()[1]
            
        srv = GstRtspServer.RTSPServer.new()
        srv.set_service(str(port))
        
        factory = GstRtspServer.RTSPMediaFactory.new()
        factory.set_launch(
            f'( udpsrc name=pay0 port={port+1} '
            f'caps="application/x-rtp, media=video, clock-rate=90000, encoding-name=H264, payload=96" )'
        )
        factory.set_shared(True)
        srv.get_mount_points().add_factory('/test', factory)
        srv.attach(None)
        print(f"✅ OK (Server instantiated and bound on test port {port})")
        return True
    except Exception as e:
        print("❌ FAIL")
        print(f"   Error details: {e}")
        return False

def run_inside_container():
    print("==================================================")
    print("   DS-SOP Inside-Container RTSP Verification   ")
    print("==================================================")
    
    checks = [
        check_gst_rtsp_server,
        check_x264enc_encoder,
        check_protobuf_stubs,
        check_gstreamer_elements,
        check_shared_libraries,
        check_rtsp_instantiation
    ]
    
    success = True
    for check in checks:
        if not check():
            success = False
        print("-" * 50)
            
    if success:
        print("\n🎉 SUCCESS: All 6 RTSP verification checks PASSED successfully!")
        sys.exit(0)
    else:
        print("\n❌ FAILED: Some RTSP verification checks did not pass. Please apply the suggested fixes.")
        sys.exit(1)

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--inside-container":
        run_inside_container()
    else:
        sys.exit(run_host_driver())

