######################################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
######################################################################################################

version: '3.8'

services:
  ddm-training-microservice:
    image: ${DDM_IMAGE:-ddm_ftms:latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DDM_PORT:-32100}:${DDM_PORT:-32100}"
    environment:
      - SERVICE_PORT=${DDM_PORT:-32100}
    volumes:
      - "./ddm:/workspace/sop-ddm-ftms/ddm" 
      - "${CONFIG_DIR:-config}:/workspace/sop-ddm-ftms/assets/config"
      - "${DATASET_ROOT:-data}:/workspace/sop-ddm-ftms/assets/data"
      - "${PRETRAINED_MODEL_ROOT:-pretrained_weights}:/workspace/sop-ddm-ftms/assets/weights"
      - "${RESULTS_ROOT:-results}:/workspace/sop-ddm-ftms/assets/results"
      - "${TOOL_PATH:-tools}:/workspace/sop-ddm-ftms/assets/tools"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    restart: unless-stopped
  metadata_db:
    image: postgres:17.2
    shm_size: 256mb # set shared memory limit when using docker compose
    volumes:
      - ${POSTGRES_DB_ROOT:-postgres_db}:/var/lib/postgresql/data
      - ./db-init-scripts/01-init-tables.sql:/docker-entrypoint-initdb.d/01-init-tables.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-sop_db}
      POSTGRES_SHARED_BUFFERS: ${POSTGRES_SHARED_BUFFERS:-64MB}
      POSTGRES_WORK_MEM: ${POSTGRES_WORK_MEM:-4MB}
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
    restart: always

  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: always

volumes:
  config:
  data:
  pretrained_weights:
  results:
  tools:
  postgres_db:

