#!/usr/bin/env bash

# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Build the DS-SOP Docker image from the ds-sop-skills-generated SOP microservice.
#
# Source code is NOT cloned from the public sop-monitoring-blueprints repo. It is
# generated by the ds-sop-skills skill (see ../ds-sop-skills/example_sop_prompt.md) into
# the `ds_sop_microservice` folder. That generated microservice already ships RTSP
# streaming output NATIVELY (the RTSP feature is owned by the ds-sop-skills skill —
# RTSPStreamingServer, the tee1-tapped output branch, the SW_ENCODER toggle, the
# api_server auto-injection, sensor_id tagging, and the Docker RTSP packages).
#
# There is therefore NO patch step here: this script just validates the generated
# layout and builds ds-sop:1.0.0. The container workdir stays /opt/nvidia/nvds_sop
# (as generated); the ds-sop compose points PYTHONPATH/working_dir/mounts there.
#
# Usage: build_ds_sop.sh [ds_sop_microservice_dir] [bp_repo_path]
#   ds_sop_microservice_dir  Path to the ds-sop-skills generated source
#                            (default: ../ds_sop_microservice relative to bp repo)
#   bp_repo_path             Path to the vss-sop blueprint repo (default: .)
set -euo pipefail

# Auto-detect and handle Docker permission issues (run under sg docker or sudo if needed)
source "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/lib/ensure_docker_access.sh"
ensure_docker_access "$@"

BP_REPO="${2:-.}"
BP_REPO="$(cd "$BP_REPO" && pwd)"

# Default the source dir to the generated ds_sop_microservice alongside the bp repo
SRC_DIR="${1:-$BP_REPO/../ds_sop_microservice}"

echo "=== DS-SOP Build: Preparing ==="

# 1. Validate the generated source exists (it is produced by the ds-sop-skills skill,
#    NOT cloned here). If missing, instruct the caller to generate it first.
if [[ ! -d "$SRC_DIR" ]]; then
  echo "❌ Error: generated SOP microservice not found at: $SRC_DIR" >&2
  echo "" >&2
  echo "Generate it first with the ds-sop-skills skill (RTSP output is opt-in — request it), e.g.:" >&2
  echo "  Follow ../ds-sop-skills/example_sop_prompt.md to generate a SOP microservice" >&2
  echo "  with rtsp streaming output feature in folder ds_sop_microservice" >&2
  echo "" >&2
  echo "Then re-run: $0 <ds_sop_microservice_dir> <bp_repo_path>" >&2
  exit 1
fi
SRC_DIR="$(cd "$SRC_DIR" && pwd)"

# Sanity-check the expected DeepStream SOP source layout (with opt-in RTSP output, ds-sop-skills § 18).
REQUIRED_FILES=(
  "docker/Docker.build"
  "deploy/compose.yaml"
  "nvds_action_detector/api_server.py"
  "nvds_action_detector/ds_3d_action_pipeline.py"
  "nvds_action_detector/ds_sop_process.py"
)
missing=0
for f in "${REQUIRED_FILES[@]}"; do
  if [[ ! -f "$SRC_DIR/$f" ]]; then
    echo "❌ Error: expected file missing from generated source: $f" >&2
    missing=1
  fi
done
if [[ "$missing" -ne 0 ]]; then
  echo "The folder at $SRC_DIR does not look like a complete ds-sop-skills generated" >&2
  echo "SOP microservice. Re-generate it with the ds-sop-skills skill before building." >&2
  exit 1
fi

echo "Using ds-sop-skills generated source: $SRC_DIR"
cd "$SRC_DIR"

# 2. Ensure the optional Pylon SDK bind-mount target exists.
echo "Ensuring binaries directory exists..."
mkdir -p binaries

# 3. Build the DS-SOP image (tag ds-sop:1.0.0; internal workdir stays nvds_sop).
echo "Building DS-SOP Docker image (ds-sop:1.0.0)..."
if docker buildx version &>/dev/null; then
  echo "Using docker buildx (BuildKit native) to build..."
  docker buildx build . -f docker/Docker.build -t ds-sop:1.0.0 --load
else
  echo "Using DOCKER_BUILDKIT=1 docker build..."
  DOCKER_BUILDKIT=1 docker build . -f docker/Docker.build -t ds-sop:1.0.0
fi

echo "=== DS-SOP Build: Completed successfully ==="

